package cn.edu.njust.dev.ses.main.model;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookID
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    private Integer bookid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookName
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    private String bookname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookType
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    private String booktype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookPrice
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    private Float bookprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publisher
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    private String publisher;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    public Book(Integer bookid, String bookname, String booktype, Float bookprice, String publisher) {
        this.bookid = bookid;
        this.bookname = bookname;
        this.booktype = booktype;
        this.bookprice = bookprice;
        this.publisher = publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    public Book() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookID
     *
     * @return the value of book.bookID
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookID
     *
     * @param bookid the value for book.bookID
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookName
     *
     * @return the value of book.bookName
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookName
     *
     * @param bookname the value for book.bookName
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    public void setBookname(String bookname) {
        this.bookname = bookname == null ? null : bookname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookType
     *
     * @return the value of book.bookType
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    public String getBooktype() {
        return booktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookType
     *
     * @param booktype the value for book.bookType
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    public void setBooktype(String booktype) {
        this.booktype = booktype == null ? null : booktype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookPrice
     *
     * @return the value of book.bookPrice
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    public Float getBookprice() {
        return bookprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookPrice
     *
     * @param bookprice the value for book.bookPrice
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    public void setBookprice(Float bookprice) {
        this.bookprice = bookprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.publisher
     *
     * @return the value of book.publisher
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.publisher
     *
     * @param publisher the value for book.publisher
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }
}