package cn.edu.njust.dev.ses.main.model;

public class Login {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.userName
     *
     * @mbg.generated Sun Mar 22 10:16:48 HKT 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.password
     *
     * @mbg.generated Sun Mar 22 10:16:48 HKT 2020
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sun Mar 22 10:16:48 HKT 2020
     */
    public Login(String username, String password) {
        this.username = username;
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sun Mar 22 10:16:48 HKT 2020
     */
    public Login() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.userName
     *
     * @return the value of login.userName
     *
     * @mbg.generated Sun Mar 22 10:16:48 HKT 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.userName
     *
     * @param username the value for login.userName
     *
     * @mbg.generated Sun Mar 22 10:16:48 HKT 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.password
     *
     * @return the value of login.password
     *
     * @mbg.generated Sun Mar 22 10:16:48 HKT 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.password
     *
     * @param password the value for login.password
     *
     * @mbg.generated Sun Mar 22 10:16:48 HKT 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}