package cn.edu.njust.dev.ses.main.model;

public class Reader {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.readerID
     *
     * @mbg.generated Sun Mar 22 11:11:37 HKT 2020
     */
    private Integer readerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.realName
     *
     * @mbg.generated Sun Mar 22 11:11:37 HKT 2020
     */
    private String realname;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Mar 22 11:11:37 HKT 2020
     */
    public Reader(Integer readerid, String realname) {
        this.readerid = readerid;
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Mar 22 11:11:37 HKT 2020
     */
    public Reader() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.readerID
     *
     * @return the value of reader.readerID
     *
     * @mbg.generated Sun Mar 22 11:11:37 HKT 2020
     */
    public Integer getReaderid() {
        return readerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.readerID
     *
     * @param readerid the value for reader.readerID
     *
     * @mbg.generated Sun Mar 22 11:11:37 HKT 2020
     */
    public void setReaderid(Integer readerid) {
        this.readerid = readerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.realName
     *
     * @return the value of reader.realName
     *
     * @mbg.generated Sun Mar 22 11:11:37 HKT 2020
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.realName
     *
     * @param realname the value for reader.realName
     *
     * @mbg.generated Sun Mar 22 11:11:37 HKT 2020
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }
}