package cn.edu.njust.dev.ses.main.mapper;

import cn.edu.njust.dev.ses.main.model.Borrow;
import cn.edu.njust.dev.ses.main.model.BorrowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BorrowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    long countByExample(BorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    int deleteByExample(BorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    int deleteByPrimaryKey(Integer recordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    int insert(Borrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    int insertSelective(Borrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    List<Borrow> selectByExampleWithRowbounds(BorrowExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    List<Borrow> selectByExample(BorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    Borrow selectByPrimaryKey(Integer recordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") Borrow record, @Param("example") BorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    int updateByExample(@Param("record") Borrow record, @Param("example") BorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    int updateByPrimaryKeySelective(Borrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    int updateByPrimaryKey(Borrow record);
}