package cn.edu.njust.dev.ses.main.mapper;

import cn.edu.njust.dev.ses.main.model.Login;

public interface LoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sun Mar 22 10:16:48 HKT 2020
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sun Mar 22 10:16:48 HKT 2020
     */
    int insert(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sun Mar 22 10:16:48 HKT 2020
     */
    int insertSelective(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sun Mar 22 10:16:48 HKT 2020
     */
    Login selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sun Mar 22 10:16:48 HKT 2020
     */
    int updateByPrimaryKeySelective(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sun Mar 22 10:16:48 HKT 2020
     */
    int updateByPrimaryKey(Login record);
}