package cn.edu.njust.dev.ses.main.mapper;

import cn.edu.njust.dev.ses.main.model.Reader;
import cn.edu.njust.dev.ses.main.model.ReaderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ReaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    long countByExample(ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    int deleteByExample(ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    int deleteByPrimaryKey(Integer readerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    int insert(Reader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    int insertSelective(Reader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    List<Reader> selectByExampleWithRowbounds(ReaderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    List<Reader> selectByExample(ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    Reader selectByPrimaryKey(Integer readerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") Reader record, @Param("example") ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    int updateByExample(@Param("record") Reader record, @Param("example") ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    int updateByPrimaryKeySelective(Reader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Mon Mar 23 02:11:42 CST 2020
     */
    int updateByPrimaryKey(Reader record);
}