package cn.edu.njust.dev.ses.main.mapper;

import cn.edu.njust.dev.ses.main.model.Reader;

public interface ReaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Mar 22 10:16:48 HKT 2020
     */
    int deleteByPrimaryKey(Integer readerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Mar 22 10:16:48 HKT 2020
     */
    int insert(Reader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Mar 22 10:16:48 HKT 2020
     */
    int insertSelective(Reader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Mar 22 10:16:48 HKT 2020
     */
    Reader selectByPrimaryKey(Integer readerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Mar 22 10:16:48 HKT 2020
     */
    int updateByPrimaryKeySelective(Reader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Mar 22 10:16:48 HKT 2020
     */
    int updateByPrimaryKey(Reader record);
}